declare const WebView:WebView;

interface WebView{
    show(options:{
        url:String,
        file:String,
        message:String,
        statusBarTranslucent:Boolean,
        asModal:Boolean,
        style:{
            width:Number,
            height:Number,
            marginVertical:Number,
            marginHorizontal:Number,
            verticalAlign:"bottom"|"top"|"middle",
            opacity:Number,
        },
        onClose(data:{message:String,store:Object}):void,
    }):void,
    useMessage(handler:(message:String)=>void):void,
    setMessage(message:String):void,
    initiateStore(store:Object,onFullfilled:(store:Object)=>void):void,
    useStore(handler:(store:Object)=>void):void,
    setStore(key:String,value:any,onFullfilled:(store:Object)=>void):void,
    close(message:String):void,
    download(params:{
        url:String
        location?:String,
        filename?:String,
        type?:String,
        toast?:String,
        onProgress(info:{
            progress:Number,
            isFinished:Boolean,
        }):void,
        onFail(message:String):void,
    }):void;
    upload(params:{
        url:string,
        body?:Object,
        toast?:String,
        encoding:"form-data",
        files:{
            path:String,
            type?:String,
            formData?:{key:String},
        }[],
        onProgress(info:{
            progress:Number,
            isFinished:Boolean,
            response?:_Response,
        }):void,
        onFail(error:{
            message:String,
            response?:_Response,
        }):void,
    }):void,
}

interface _Response{
    protocol:String,
    code:Number,
    message:String,
    url:String,
    isSuccessful:Boolean,
    body:String|Object,
}
